//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: users.proto

package users;

@kotlin.jvm.JvmName("-initializesocialAccount")
public inline fun socialAccount(block: users.SocialAccountKt.Dsl.() -> kotlin.Unit): users.Users.SocialAccount =
  users.SocialAccountKt.Dsl._create(users.Users.SocialAccount.newBuilder()).apply { block() }._build()
public object SocialAccountKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: users.Users.SocialAccount.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: users.Users.SocialAccount.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): users.Users.SocialAccount = _builder.build()

    /**
     * <code>int64 id = 1;</code>
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>int64 id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string provider = 2;</code>
     */
    public var provider: kotlin.String
      @JvmName("getProvider")
      get() = _builder.getProvider()
      @JvmName("setProvider")
      set(value) {
        _builder.setProvider(value)
      }
    /**
     * <code>string provider = 2;</code>
     */
    public fun clearProvider() {
      _builder.clearProvider()
    }

    /**
     * <code>string accountId = 3;</code>
     */
    public var accountId: kotlin.String
      @JvmName("getAccountId")
      get() = _builder.getAccountId()
      @JvmName("setAccountId")
      set(value) {
        _builder.setAccountId(value)
      }
    /**
     * <code>string accountId = 3;</code>
     */
    public fun clearAccountId() {
      _builder.clearAccountId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun users.Users.SocialAccount.copy(block: users.SocialAccountKt.Dsl.() -> kotlin.Unit): users.Users.SocialAccount =
  users.SocialAccountKt.Dsl._create(this.toBuilder()).apply { block() }._build()

