// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package users;

@kotlin.jvm.JvmName("-initializesubscriptionEntity")
public inline fun subscriptionEntity(block: users.SubscriptionEntityKt.Dsl.() -> kotlin.Unit): users.Users.SubscriptionEntity =
  users.SubscriptionEntityKt.Dsl._create(users.Users.SubscriptionEntity.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message definitions
 * ```
 *
 * Protobuf type `users.SubscriptionEntity`
 */
public object SubscriptionEntityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: users.Users.SubscriptionEntity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: users.Users.SubscriptionEntity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): users.Users.SubscriptionEntity = _builder.build()

    /**
     * `int64 id = 1;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `int64 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string description = 3;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * `string description = 3;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `double price = 4;`
     */
    public var price: kotlin.Double
      @JvmName("getPrice")
      get() = _builder.getPrice()
      @JvmName("setPrice")
      set(value) {
        _builder.setPrice(value)
      }
    /**
     * `double price = 4;`
     */
    public fun clearPrice() {
      _builder.clearPrice()
    }

    /**
     * `int32 duration_days = 5;`
     */
    public var durationDays: kotlin.Int
      @JvmName("getDurationDays")
      get() = _builder.getDurationDays()
      @JvmName("setDurationDays")
      set(value) {
        _builder.setDurationDays(value)
      }
    /**
     * `int32 duration_days = 5;`
     */
    public fun clearDurationDays() {
      _builder.clearDurationDays()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun users.Users.SubscriptionEntity.copy(block: `users`.SubscriptionEntityKt.Dsl.() -> kotlin.Unit): users.Users.SubscriptionEntity =
  `users`.SubscriptionEntityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

