//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: users.proto

package users;

@kotlin.jvm.JvmName("-initializeuserSubscription")
public inline fun userSubscription(block: users.UserSubscriptionKt.Dsl.() -> kotlin.Unit): users.Users.UserSubscription =
  users.UserSubscriptionKt.Dsl._create(users.Users.UserSubscription.newBuilder()).apply { block() }._build()
public object UserSubscriptionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: users.Users.UserSubscription.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: users.Users.UserSubscription.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): users.Users.UserSubscription = _builder.build()

    /**
     * <code>int64 id = 1;</code>
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>int64 id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string subscriptionType = 2;</code>
     */
    public var subscriptionType: kotlin.String
      @JvmName("getSubscriptionType")
      get() = _builder.getSubscriptionType()
      @JvmName("setSubscriptionType")
      set(value) {
        _builder.setSubscriptionType(value)
      }
    /**
     * <code>string subscriptionType = 2;</code>
     */
    public fun clearSubscriptionType() {
      _builder.clearSubscriptionType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun users.Users.UserSubscription.copy(block: users.UserSubscriptionKt.Dsl.() -> kotlin.Unit): users.Users.UserSubscription =
  users.UserSubscriptionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

