//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: users.proto

package users;

@kotlin.jvm.JvmName("-initializeusersEntity")
public inline fun usersEntity(block: users.UsersEntityKt.Dsl.() -> kotlin.Unit): users.Users.UsersEntity =
  users.UsersEntityKt.Dsl._create(users.Users.UsersEntity.newBuilder()).apply { block() }._build()
public object UsersEntityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: users.Users.UsersEntity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: users.Users.UsersEntity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): users.Users.UsersEntity = _builder.build()

    /**
     * <code>int64 id = 1;</code>
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>int64 id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string email = 2;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>string email = 2;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * <code>string password = 3;</code>
     */
    public var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * <code>string password = 3;</code>
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }

    /**
     * <code>string name = 4;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 4;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>.users.Role role = 5;</code>
     */
    public var role: users.Users.Role
      @JvmName("getRole")
      get() = _builder.getRole()
      @JvmName("setRole")
      set(value) {
        _builder.setRole(value)
      }
    /**
     * <code>.users.Role role = 5;</code>
     */
    public fun clearRole() {
      _builder.clearRole()
    }

    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    public var createdAt: com.google.protobuf.Timestamp
      @JvmName("getCreatedAt")
      get() = _builder.getCreatedAt()
      @JvmName("setCreatedAt")
      set(value) {
        _builder.setCreatedAt(value)
      }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    public var updatedAt: com.google.protobuf.Timestamp
      @JvmName("getUpdatedAt")
      get() = _builder.getUpdatedAt()
      @JvmName("setUpdatedAt")
      set(value) {
        _builder.setUpdatedAt(value)
      }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     * @return Whether the updatedAt field is set.
     */
    public fun hasUpdatedAt(): kotlin.Boolean {
      return _builder.hasUpdatedAt()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EmailsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .users.UserEmail emails = 8;</code>
     */
     public val emails: com.google.protobuf.kotlin.DslList<users.Users.UserEmail, EmailsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEmailsList()
      )
    /**
     * <code>repeated .users.UserEmail emails = 8;</code>
     * @param value The emails to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEmails")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserEmail, EmailsProxy>.add(value: users.Users.UserEmail) {
      _builder.addEmails(value)
    }
    /**
     * <code>repeated .users.UserEmail emails = 8;</code>
     * @param value The emails to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEmails")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.UserEmail, EmailsProxy>.plusAssign(value: users.Users.UserEmail) {
      add(value)
    }
    /**
     * <code>repeated .users.UserEmail emails = 8;</code>
     * @param values The emails to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEmails")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserEmail, EmailsProxy>.addAll(values: kotlin.collections.Iterable<users.Users.UserEmail>) {
      _builder.addAllEmails(values)
    }
    /**
     * <code>repeated .users.UserEmail emails = 8;</code>
     * @param values The emails to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEmails")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.UserEmail, EmailsProxy>.plusAssign(values: kotlin.collections.Iterable<users.Users.UserEmail>) {
      addAll(values)
    }
    /**
     * <code>repeated .users.UserEmail emails = 8;</code>
     * @param index The index to set the value at.
     * @param value The emails to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEmails")
    public operator fun com.google.protobuf.kotlin.DslList<users.Users.UserEmail, EmailsProxy>.set(index: kotlin.Int, value: users.Users.UserEmail) {
      _builder.setEmails(index, value)
    }
    /**
     * <code>repeated .users.UserEmail emails = 8;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEmails")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserEmail, EmailsProxy>.clear() {
      _builder.clearEmails()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SocialAccountsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .users.SocialAccount social_accounts = 9;</code>
     */
     public val socialAccounts: com.google.protobuf.kotlin.DslList<users.Users.SocialAccount, SocialAccountsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSocialAccountsList()
      )
    /**
     * <code>repeated .users.SocialAccount social_accounts = 9;</code>
     * @param value The socialAccounts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSocialAccounts")
    public fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccount, SocialAccountsProxy>.add(value: users.Users.SocialAccount) {
      _builder.addSocialAccounts(value)
    }
    /**
     * <code>repeated .users.SocialAccount social_accounts = 9;</code>
     * @param value The socialAccounts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSocialAccounts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccount, SocialAccountsProxy>.plusAssign(value: users.Users.SocialAccount) {
      add(value)
    }
    /**
     * <code>repeated .users.SocialAccount social_accounts = 9;</code>
     * @param values The socialAccounts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSocialAccounts")
    public fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccount, SocialAccountsProxy>.addAll(values: kotlin.collections.Iterable<users.Users.SocialAccount>) {
      _builder.addAllSocialAccounts(values)
    }
    /**
     * <code>repeated .users.SocialAccount social_accounts = 9;</code>
     * @param values The socialAccounts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSocialAccounts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccount, SocialAccountsProxy>.plusAssign(values: kotlin.collections.Iterable<users.Users.SocialAccount>) {
      addAll(values)
    }
    /**
     * <code>repeated .users.SocialAccount social_accounts = 9;</code>
     * @param index The index to set the value at.
     * @param value The socialAccounts to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSocialAccounts")
    public operator fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccount, SocialAccountsProxy>.set(index: kotlin.Int, value: users.Users.SocialAccount) {
      _builder.setSocialAccounts(index, value)
    }
    /**
     * <code>repeated .users.SocialAccount social_accounts = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSocialAccounts")
    public fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccount, SocialAccountsProxy>.clear() {
      _builder.clearSocialAccounts()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SubscriptionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .users.UserSubscription subscriptions = 10;</code>
     */
     public val subscriptions: com.google.protobuf.kotlin.DslList<users.Users.UserSubscription, SubscriptionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSubscriptionsList()
      )
    /**
     * <code>repeated .users.UserSubscription subscriptions = 10;</code>
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscription, SubscriptionsProxy>.add(value: users.Users.UserSubscription) {
      _builder.addSubscriptions(value)
    }
    /**
     * <code>repeated .users.UserSubscription subscriptions = 10;</code>
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSubscriptions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscription, SubscriptionsProxy>.plusAssign(value: users.Users.UserSubscription) {
      add(value)
    }
    /**
     * <code>repeated .users.UserSubscription subscriptions = 10;</code>
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscription, SubscriptionsProxy>.addAll(values: kotlin.collections.Iterable<users.Users.UserSubscription>) {
      _builder.addAllSubscriptions(values)
    }
    /**
     * <code>repeated .users.UserSubscription subscriptions = 10;</code>
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSubscriptions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscription, SubscriptionsProxy>.plusAssign(values: kotlin.collections.Iterable<users.Users.UserSubscription>) {
      addAll(values)
    }
    /**
     * <code>repeated .users.UserSubscription subscriptions = 10;</code>
     * @param index The index to set the value at.
     * @param value The subscriptions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSubscriptions")
    public operator fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscription, SubscriptionsProxy>.set(index: kotlin.Int, value: users.Users.UserSubscription) {
      _builder.setSubscriptions(index, value)
    }
    /**
     * <code>repeated .users.UserSubscription subscriptions = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscription, SubscriptionsProxy>.clear() {
      _builder.clearSubscriptions()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun users.Users.UsersEntity.copy(block: users.UsersEntityKt.Dsl.() -> kotlin.Unit): users.Users.UsersEntity =
  users.UsersEntityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val users.Users.UsersEntityOrBuilder.createdAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

val users.Users.UsersEntityOrBuilder.updatedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasUpdatedAt()) getUpdatedAt() else null

