// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package users;

@kotlin.jvm.JvmName("-initializeuserEmailEntity")
public inline fun userEmailEntity(block: users.UserEmailEntityKt.Dsl.() -> kotlin.Unit): users.Users.UserEmailEntity =
  users.UserEmailEntityKt.Dsl._create(users.Users.UserEmailEntity.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `users.UserEmailEntity`
 */
public object UserEmailEntityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: users.Users.UserEmailEntity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: users.Users.UserEmailEntity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): users.Users.UserEmailEntity = _builder.build()

    /**
     * `int64 id = 1;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `int64 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `.users.UsersEntity user = 2;`
     */
    public var user: users.Users.UsersEntity
      @JvmName("getUser")
      get() = _builder.getUser()
      @JvmName("setUser")
      set(value) {
        _builder.setUser(value)
      }
    /**
     * `.users.UsersEntity user = 2;`
     */
    public fun clearUser() {
      _builder.clearUser()
    }
    /**
     * `.users.UsersEntity user = 2;`
     * @return Whether the user field is set.
     */
    public fun hasUser(): kotlin.Boolean {
      return _builder.hasUser()
    }
    public val UserEmailEntityKt.Dsl.userOrNull: users.Users.UsersEntity?
      get() = _builder.userOrNull

    /**
     * `string email = 3;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * `string email = 3;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `bool verified = 4;`
     */
    public var verified: kotlin.Boolean
      @JvmName("getVerified")
      get() = _builder.getVerified()
      @JvmName("setVerified")
      set(value) {
        _builder.setVerified(value)
      }
    /**
     * `bool verified = 4;`
     */
    public fun clearVerified() {
      _builder.clearVerified()
    }

    /**
     * `string created_at = 5;`
     */
    public var createdAt: kotlin.String
      @JvmName("getCreatedAt")
      get() = _builder.getCreatedAt()
      @JvmName("setCreatedAt")
      set(value) {
        _builder.setCreatedAt(value)
      }
    /**
     * `string created_at = 5;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun users.Users.UserEmailEntity.copy(block: `users`.UserEmailEntityKt.Dsl.() -> kotlin.Unit): users.Users.UserEmailEntity =
  `users`.UserEmailEntityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val users.Users.UserEmailEntityOrBuilder.userOrNull: users.Users.UsersEntity?
  get() = if (hasUser()) getUser() else null

