//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: users.proto

package users;

@kotlin.jvm.JvmName("-initializeuserEmail")
public inline fun userEmail(block: users.UserEmailKt.Dsl.() -> kotlin.Unit): users.Users.UserEmail =
  users.UserEmailKt.Dsl._create(users.Users.UserEmail.newBuilder()).apply { block() }._build()
public object UserEmailKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: users.Users.UserEmail.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: users.Users.UserEmail.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): users.Users.UserEmail = _builder.build()

    /**
     * <code>int64 id = 1;</code>
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>int64 id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string email = 2;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>string email = 2;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun users.Users.UserEmail.copy(block: users.UserEmailKt.Dsl.() -> kotlin.Unit): users.Users.UserEmail =
  users.UserEmailKt.Dsl._create(this.toBuilder()).apply { block() }._build()

