// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package users;

@kotlin.jvm.JvmName("-initializeusersEntity")
public inline fun usersEntity(block: users.UsersEntityKt.Dsl.() -> kotlin.Unit): users.Users.UsersEntity =
  users.UsersEntityKt.Dsl._create(users.Users.UsersEntity.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `users.UsersEntity`
 */
public object UsersEntityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: users.Users.UsersEntity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: users.Users.UsersEntity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): users.Users.UsersEntity = _builder.build()

    /**
     * `int64 id = 1;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `int64 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string email = 2;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * `string email = 2;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `string password = 3;`
     */
    public var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * `string password = 3;`
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }

    /**
     * `string name = 4;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 4;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.users.Role role = 5;`
     */
    public var role: users.Users.Role
      @JvmName("getRole")
      get() = _builder.getRole()
      @JvmName("setRole")
      set(value) {
        _builder.setRole(value)
      }
    public var roleValue: kotlin.Int
      @JvmName("getRoleValue")
      get() = _builder.getRoleValue()
      @JvmName("setRoleValue")
      set(value) {
        _builder.setRoleValue(value)
      }
    /**
     * `.users.Role role = 5;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }

    /**
     * `string created_at = 6;`
     */
    public var createdAt: kotlin.String
      @JvmName("getCreatedAt")
      get() = _builder.getCreatedAt()
      @JvmName("setCreatedAt")
      set(value) {
        _builder.setCreatedAt(value)
      }
    /**
     * `string created_at = 6;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }

    /**
     * `string updated_at = 7;`
     */
    public var updatedAt: kotlin.String
      @JvmName("getUpdatedAt")
      get() = _builder.getUpdatedAt()
      @JvmName("setUpdatedAt")
      set(value) {
        _builder.setUpdatedAt(value)
      }
    /**
     * `string updated_at = 7;`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EmailsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .users.UserEmailEntity emails = 8;`
     */
     public val emails: com.google.protobuf.kotlin.DslList<users.Users.UserEmailEntity, EmailsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEmailsList()
      )
    /**
     * `repeated .users.UserEmailEntity emails = 8;`
     * @param value The emails to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEmails")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserEmailEntity, EmailsProxy>.add(value: users.Users.UserEmailEntity) {
      _builder.addEmails(value)
    }
    /**
     * `repeated .users.UserEmailEntity emails = 8;`
     * @param value The emails to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEmails")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.UserEmailEntity, EmailsProxy>.plusAssign(value: users.Users.UserEmailEntity) {
      add(value)
    }
    /**
     * `repeated .users.UserEmailEntity emails = 8;`
     * @param values The emails to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEmails")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserEmailEntity, EmailsProxy>.addAll(values: kotlin.collections.Iterable<users.Users.UserEmailEntity>) {
      _builder.addAllEmails(values)
    }
    /**
     * `repeated .users.UserEmailEntity emails = 8;`
     * @param values The emails to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEmails")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.UserEmailEntity, EmailsProxy>.plusAssign(values: kotlin.collections.Iterable<users.Users.UserEmailEntity>) {
      addAll(values)
    }
    /**
     * `repeated .users.UserEmailEntity emails = 8;`
     * @param index The index to set the value at.
     * @param value The emails to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEmails")
    public operator fun com.google.protobuf.kotlin.DslList<users.Users.UserEmailEntity, EmailsProxy>.set(index: kotlin.Int, value: users.Users.UserEmailEntity) {
      _builder.setEmails(index, value)
    }
    /**
     * `repeated .users.UserEmailEntity emails = 8;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEmails")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserEmailEntity, EmailsProxy>.clear() {
      _builder.clearEmails()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SocialAccountsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .users.SocialAccountEntity social_accounts = 9;`
     */
     public val socialAccounts: com.google.protobuf.kotlin.DslList<users.Users.SocialAccountEntity, SocialAccountsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSocialAccountsList()
      )
    /**
     * `repeated .users.SocialAccountEntity social_accounts = 9;`
     * @param value The socialAccounts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSocialAccounts")
    public fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccountEntity, SocialAccountsProxy>.add(value: users.Users.SocialAccountEntity) {
      _builder.addSocialAccounts(value)
    }
    /**
     * `repeated .users.SocialAccountEntity social_accounts = 9;`
     * @param value The socialAccounts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSocialAccounts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccountEntity, SocialAccountsProxy>.plusAssign(value: users.Users.SocialAccountEntity) {
      add(value)
    }
    /**
     * `repeated .users.SocialAccountEntity social_accounts = 9;`
     * @param values The socialAccounts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSocialAccounts")
    public fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccountEntity, SocialAccountsProxy>.addAll(values: kotlin.collections.Iterable<users.Users.SocialAccountEntity>) {
      _builder.addAllSocialAccounts(values)
    }
    /**
     * `repeated .users.SocialAccountEntity social_accounts = 9;`
     * @param values The socialAccounts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSocialAccounts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccountEntity, SocialAccountsProxy>.plusAssign(values: kotlin.collections.Iterable<users.Users.SocialAccountEntity>) {
      addAll(values)
    }
    /**
     * `repeated .users.SocialAccountEntity social_accounts = 9;`
     * @param index The index to set the value at.
     * @param value The socialAccounts to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSocialAccounts")
    public operator fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccountEntity, SocialAccountsProxy>.set(index: kotlin.Int, value: users.Users.SocialAccountEntity) {
      _builder.setSocialAccounts(index, value)
    }
    /**
     * `repeated .users.SocialAccountEntity social_accounts = 9;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSocialAccounts")
    public fun com.google.protobuf.kotlin.DslList<users.Users.SocialAccountEntity, SocialAccountsProxy>.clear() {
      _builder.clearSocialAccounts()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SubscriptionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .users.UserSubscriptionEntity subscriptions = 10;`
     */
     public val subscriptions: com.google.protobuf.kotlin.DslList<users.Users.UserSubscriptionEntity, SubscriptionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSubscriptionsList()
      )
    /**
     * `repeated .users.UserSubscriptionEntity subscriptions = 10;`
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscriptionEntity, SubscriptionsProxy>.add(value: users.Users.UserSubscriptionEntity) {
      _builder.addSubscriptions(value)
    }
    /**
     * `repeated .users.UserSubscriptionEntity subscriptions = 10;`
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSubscriptions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscriptionEntity, SubscriptionsProxy>.plusAssign(value: users.Users.UserSubscriptionEntity) {
      add(value)
    }
    /**
     * `repeated .users.UserSubscriptionEntity subscriptions = 10;`
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscriptionEntity, SubscriptionsProxy>.addAll(values: kotlin.collections.Iterable<users.Users.UserSubscriptionEntity>) {
      _builder.addAllSubscriptions(values)
    }
    /**
     * `repeated .users.UserSubscriptionEntity subscriptions = 10;`
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSubscriptions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscriptionEntity, SubscriptionsProxy>.plusAssign(values: kotlin.collections.Iterable<users.Users.UserSubscriptionEntity>) {
      addAll(values)
    }
    /**
     * `repeated .users.UserSubscriptionEntity subscriptions = 10;`
     * @param index The index to set the value at.
     * @param value The subscriptions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSubscriptions")
    public operator fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscriptionEntity, SubscriptionsProxy>.set(index: kotlin.Int, value: users.Users.UserSubscriptionEntity) {
      _builder.setSubscriptions(index, value)
    }
    /**
     * `repeated .users.UserSubscriptionEntity subscriptions = 10;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<users.Users.UserSubscriptionEntity, SubscriptionsProxy>.clear() {
      _builder.clearSubscriptions()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun users.Users.UsersEntity.copy(block: `users`.UsersEntityKt.Dsl.() -> kotlin.Unit): users.Users.UsersEntity =
  `users`.UsersEntityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

