# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n\tUserEmail\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"@\n\rSocialAccount\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x11\n\taccountId\x18\x03 \x01(\t\"8\n\x10UserSubscription\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x18\n\x10subscriptionType\x18\x02 \x01(\t\"\xc4\x02\n\x0bUsersEntity\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x19\n\x04role\x18\x05 \x01(\x0e\x32\x0b.users.Role\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12 \n\x06\x65mails\x18\x08 \x03(\x0b\x32\x10.users.UserEmail\x12-\n\x0fsocial_accounts\x18\t \x03(\x0b\x32\x14.users.SocialAccount\x12.\n\rsubscriptions\x18\n \x03(\x0b\x32\x17.users.UserSubscription*\x1b\n\x04Role\x12\x08\n\x04USER\x10\x00\x12\t\n\x05\x41\x44MIN\x10\x01\x42.Z,github.com/YouSangSon/ys_models/golang/usersb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/YouSangSon/ys_models/golang/users'
  _ROLE._serialized_start=546
  _ROLE._serialized_end=573
  _USEREMAIL._serialized_start=55
  _USEREMAIL._serialized_end=93
  _SOCIALACCOUNT._serialized_start=95
  _SOCIALACCOUNT._serialized_end=159
  _USERSUBSCRIPTION._serialized_start=161
  _USERSUBSCRIPTION._serialized_end=217
  _USERSENTITY._serialized_start=220
  _USERSENTITY._serialized_end=544
# @@protoc_insertion_point(module_scope)
